site_name: Java Features
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: red
      accent: amber
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: red
      accent: amber
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking

docs_dir: ./docs
extra:
  generator: false
nav:
  - Java8: "8"
  - Java9: "9"
  - Java10: "10"
  - Java11: "11"
  - Java12: "12"
  - Java13: "13"
  - Java14: "14"
  - Java15: "15"
  - Java16: "16"
  - Java17: "17"

site_dir: ./build
site_url: https://mehmetumit.github.io/JavaFeatures/
repo_url: https://github.com/mehmetumit/JavaFeatures
